### ISSUE TITLE
Bad Gateway when use docker image with reverse proxy

### ISSUE THREAD

**Issue by Sonic3R** [jee-r/docker-glowing-bear#18]
Hi,

I have the following docker container:

```
  glowing-bear:
    container_name: glowing-bear
    image: 'j33r/glowing-bear:latest'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - VIRTUAL_HOST=my.domain.com
      - VIRTUAL_PORT=9912
      - LETSENCRYPT_HOST=my.domain.com
    ports:
      - '8080:9912'
    restart: always
```

I see bad gateway page and don't understand why

I want to connect to normal installed weechat (not dockerized container) and I opened a relay on port 9911 (`/relay add weechat 9911`) and set password (`/set relay.network.password ABCDEF`)

**Comment by jee-r** [comment]
Hello @Sonic3R,

I’m not sure where the environment variables `VIRTUAL_HOST`, `VIRTUAL_PORT`, and `LETSENCRYPT_HOST` are coming from, as they are not needed for running the `glowing-bear` Docker image.

To run the `glowing-bear` container, you only need to expose port `8080` to your host and then connect to `http://127.0.0.1:8080`. There is no built-in Let's Encrypt feature in the image. If you need HTTPS, you'll have to run a reverse proxy (like NGINX) in front of the container to handle SSL and manage the HTTPS connection.

Here is an example `docker-compose` configuration that should work out of the box:

```yaml
glowing-bear:
    container_name: glowing-bear
    image: 'j33r/glowing-bear:latest'
    environment:
      - TZ=Europe/Bucharest
    ports:
      - '8080:8080'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
```

With this configuration, you can directly access the app via http://127.0.0.1:8080.

Note: Even the `PUID` and `PGID` variables are not necessary, as the [nginx-unprivileged image](https://github.com/nginxinc/docker-nginx-unprivileged) is rootless by design.

**Comment by Sonic3R** [comment]
Hi, thanks for reply

I use the following images that I use for reverse proxy and nginx:

```
nginx-proxy:
image: 'jwilder/nginx-proxy:latest'
container_name: nginx-proxy
volumes:
 - /etc/nginx/certs
 - /etc/nginx/vhost.d
 - /usr/share/nginx/html
 - '/var/run/docker.sock:/tmp/docker.sock:ro'
 - '/opt/nginx/htpasswd:/etc/nginx/htpasswd'
ports:
 - '80:80'
 - '443:443'
restart: always
letsencrypt:
image: 'jrcs/letsencrypt-nginx-proxy-companion:>
container_name: letsencrypt
volumes:
 - '/var/run/docker.sock:/var/run/docker.sock:>
volumes_from:
 - nginx-proxy
restart: always
```

I want to access website through my.domain.com instead of local host or whatever, that’s why I use virtual port and lets encrypt

**Comment by jee-r** [comment]
ok i don't know how this image works but in my image [only `8080` port is exposed ](https://github.com/jee-r/docker-glowing-bear/blob/489cf6db8cb2a387d25928bae4cea55122b8231d/Dockerfile#L21C11-L21C12)
 
 
 so  based on your first message this should work :
 
 ```yaml
 glowing-bear:
    container_name: glowing-bear
    image: 'j33r/glowing-bear:latest'
    environment:
      - TZ=Europe/Bucharest      
      - VIRTUAL_HOST=my.domain.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=my.domain.com
    ports:
      - '8080:8080'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
```
